vacation_log/config/routes.rb
Rails.application.routes.draw do
   resources :events do
    resources :contributions
  end

  root 'events#index'

  get 'events/:id/like', to: 'places#like', as: :like

end

vacation_log/app/models/contribution.rb
class Contribution < ActiveRecord::Base
	belongs_to :event
    has_attached_file :photo, :styles => { :larger => '400x400', :medium => "200x200>", :thumb => "100x100>" },:default_url => '/system/users/avatars/missing.jpg'
	validates_attachment_presence :photo  
validates_attachment_size :photo, :less_than => 5.megabytes  
validates_attachment_content_type :photo, :content_type => ['image/jpeg', 'image/png']  

end

vacation_log/app/models/event.rb
class Event < ActiveRecord::Base
	has_many :contributions


end

vacation_log/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

vacation_log/app/controllers/contributions_controller.rb
class ContributionsController < ApplicationController
	def create
		@event = Event.find(params[:event_id])
		@contribution = @event.contributions.create(contribution_params)
		redirect_to event_path(@event)
	end

	def destroy
		@event = Event.find(params[:event_id])
    	@contribution = @event.contributions.find(params[:id])
    	@contribution.destroy
    	redirect_to event_path(@event)
	end

	def edit
		@event = Event.find(params[:event_id])
		@contribution = @event.contributions.find(params[:id])
	end

	def update
		@event = Event.find(params[:id])
		@contribution = @event.contributions.find(params[:id])
		if @contribution.update(contribution_params)
			redirect_to @event
		else
			render 'edit'
		end
	end

	def show
		@event = Event.find(params[:event_id])
		@contributions = @event.contributions.find(params[:id])
	end

	private
	def contribution_params
		params.require(:contribution).permit(:text, :contributor, :photo)
	end
end

vacation_log/app/controllers/events_controller.rb
class EventsController < ApplicationController
	def index
		@events = Event.all
	end

	def create
		@event = Event.new(event_params)
		if @event.save
			redirect_to event_path(@event)
		else
			render :new
		end
	end

	def new
		@event = Event.new
		@contributions = @event.contributions
	end

	def edit
		@event = Event.find(params[:id])
	end

	def show
		@event = Event.find(params[:id])
		@contributions = @event.contributions
	end

	def update
		@event = Event.find(params[:id])
		if @event.update(event_params)
			redirect_to @event
		else
			render 'edit'
		end
	end

	def destroy
		@event = Event.find(params[:id])
		@event.destroy

		redirect_to events_path
	end

	def like
		@event = Event.find(params[:id])

		@event.likes += 1
		@event.save
		redirect_to events_path
	end

	private
	def event_params 
		event_params = params.require(:event).permit(:name, :date, :rating, :likes)
	end
end

vacation_log/app/helpers/application_helper.rb
module ApplicationHelper
end

vacation_log/app/views/contributions/_comment.html.erb
<%@event.contributions.each do |contribution| %>
<p> Name: <%=contribution.contributor%> <br>
			<%=contribution.text%> 
			<%=image_tag @contribution.avatar.url(:large) %></p>
<%end%>

vacation_log/app/views/contributions/_contribution.html.erb
<p>
	<h2> <%=contribution.contributor%> </h2> <br>
			<%= image_tag contribution.photo(:larger) %> </br> </br>
			<%=contribution.text%> </p>

			 <%= link_to 'Delete Contribution', [contribution.event, contribution],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>

    <hr>

vacation_log/app/views/contributions/_form.html.erb
<%= bootstrap_form_for([@event, @event.contributions.build], :multipart => true) do |f| %>
<% if @event.errors.present? %>
	<% @event.contributions.errors.full_messages.each do |msg| %>
		<p> <%= msg %> </p>
	<%end%>
<%end%>

  <%= f.text_field :contributor %>
  <%= f.text_field :text %>
  <%= f.file_field :photo %>
  <%= f.submit "Submit" %>
<% end %>

vacation_log/app/views/contributions/edit.html.erb
<h1> Edit <%=@contribution.contributor%> </h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

vacation_log/app/views/contributions/show.html.erb
<%= render 'form' %>

vacation_log/app/views/events/_form.html.erb
<%= bootstrap_form_for(@event) do |f| %>
<% if @event.errors.present? %>
	<% @event.errors.full_messages.each do |msg| %>
		<p> <%= msg %> </p>
	<%end%>
<%end%>

  <%= f.text_field :name %>
  <%= f.text_field :date %>
  <%= f.number_field :rating %>
  <%= f.submit "Submit" %>
<% end %>

vacation_log/app/views/events/edit.html.erb
<h1> Edit <%=@event.name%> </h1>

<%= render 'form' %>

vacation_log/app/views/events/index.html.erb
<div class="text-center col-md-6 col-md-offset-3">
<table class="table table-striped table-hover">
<header class="text-center"> 
<div>
	<h1> Vacation Highlights </h1>
	
</div>
</header>

<% @events.each do |event|%>
<p>
	<tr> 
		<td> <%= link_to event.name, event_path(event)%> </td>
		<td> <%= event.date %> </td>
		<td> <%= link_to 'Edit', edit_event_path(event) %> </td>
		<td> <%= link_to 'Delete', event_path(event), method: :delete, data: { confirm: 'Are you sure?' } %> </td>
	</tr>
	</p>


<%end%>
</table>
<%= link_to 'New', new_event_path %>
</div>

vacation_log/app/views/events/new.html.erb
<div class="col-md-10">
<h1> New Event </h1>

<%= render 'form' %>
</br>

<%= link_to 'Back', events_path %>
</div>

vacation_log/app/views/events/show.html.erb
<div class="text-center">
<h1> <strong> <%=@event.name %> </strong> </h1> 
<h1> <small> <%= @event.date %> </small> </h1>
<hr>
</div>

<div class="col-md-10">
<%= render @event.contributions %>
<%= render 'contributions/form' %>



<%= link_to 'Back to Events', events_path %> 
<td><%= link_to 'Delete Event', event_path(@event), method: :delete, data: { confirm: 'Are you sure?' } %></td> 
<%= link_to 'Edit Event', edit_event_path%>
</div>

vacation_log/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>VacationLog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>



<%= yield %>

</body>
</html>